apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFAzCCA+ugAwIBAgISBuVSTEZL5XcHfLA0/qIvJceRMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTIwHhcNMjUwOTA4MTQzNDMwWhcNMjUxMjA3MTQzNDI5WjAeMRwwGgYDVQQD
    ExNpbmZyYS0zNDAwMC5jYXN0LmZyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAof41blMIWlrDvhpKzi0OBF5Jnsg5Vvn9sixAF95yYN6QjfqyhAbGxKyQ
    CurWrzPYaA2xD9kkdNtcns7Wco4LBX9wVY/gwubBQSA6ZMNjWdJnT0bLNmXBHkWy
    tWBaF+Axmcqzj893vOIdxrpuqK9cpHdLOqAA7S8Aly/swxbWYsUPiw0fx/np76tw
    0coNFgpV7uo1haUGEX07ffRwHdViuddOhiHsybt+Tpnjt6Wi/Z+neFeV2gZntuXY
    n1v2z5J+ODynzpM6pGckO7ajVaSv5ETGGsiG8XFBJ50eX+i/R3hzRzH2k7lKnRd9
    Z9OG1qHtiPuCch9gG+LT5lZMFEPWbwIDAQABo4ICJDCCAiAwDgYDVR0PAQH/BAQD
    AgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA
    MB0GA1UdDgQWBBRk0CZIdju03ItGCCk6jk46KOTr3jAfBgNVHSMEGDAWgBQAtSny
    LY5vMeibTK14Pvrc6QzR0jAzBggrBgEFBQcBAQQnMCUwIwYIKwYBBQUHMAKGF2h0
    dHA6Ly9yMTIuaS5sZW5jci5vcmcvMB4GA1UdEQQXMBWCE2luZnJhLTM0MDAwLmNh
    c3QuZnIwEwYDVR0gBAwwCjAIBgZngQwBAgEwLgYDVR0fBCcwJTAjoCGgH4YdaHR0
    cDovL3IxMi5jLmxlbmNyLm9yZy8xOC5jcmwwggEFBgorBgEEAdZ5AgQCBIH2BIHz
    APEAdwDtPEvW6AbCpKIAV9vLJOI4Ad9RL+3EhsVwDyDdtz4/4AAAAZkp9Yf7AAAE
    AwBIMEYCIQC+beQ3hT9Bp8erFa4k+LMmrPCNgLy3hYBAV4uP0sRvsQIhAMfM3S1d
    gpLV+iAWeQu0VQnwi99Uoavas4KfHpizBCBIAHYADeHyMCvTDcFAYhIJ6lUu/Ed0
    fLHX6TDvDkIetH5OqjQAAAGZKfWH3gAABAMARzBFAiA6n7CEvlkzso8tBIvTkbVq
    5w1I5/mKfqHxze1crM8iAQIhAMsEREnt5by+b5eW5awQSaq85jVX1aKw+ELaRDNt
    NL1sMA0GCSqGSIb3DQEBCwUAA4IBAQCiHGTwHTm4MiOeBhQBC9oQvfbi0aoxLABS
    uPwzTEe4lqj5bLcAwoymd2R1OqLq9w2863FwMgSHkv370HeJ91A8N/L3IFoUUkOE
    jqVtAbWnVemM9dKFIxu38phXZm9qlbW3pxwA1jkN99WwR/vrqSGa9KOEsyal8yuN
    4SFLYnpetpx0R0lcImPcmgqmHbvypbxJyvG7JZUfzfOQIK1dxKWCxxpZIZ2V0Oz/
    TBb5NTbzRpaxP645kWEk7fx+Zrr5ulJFuRfx5dgBlErG9ae0qJvrQdTpFeJLyufe
    z6q2SfcGY4SEarNjZ2rKttud2A5yIA5IEyn2DLhE9Gxhmt8tkKv+
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: authcacrt
  namespace: {{.Release.Namespace}}