apiVersion: v1
kind: Service
metadata:
  name: console-analysis-node
  labels:
    app: castimaging
    imaging.service: console-analysis-node
    component: core
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    imaging.service: console-analysis-node
    component: core
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: castimaging
    imaging.service: console-analysis-node
    version: {{ .Values.ConsoleAnalysisNodeImage.tag| default .Values.version }}
  name: console-analysis-node-core
  namespace: {{ .Release.Namespace }}   
spec:
  serviceName: console-analysis-node
  replicas: {{ .Values.AnalysisNodeReplicaCount }}
  selector:
    matchLabels:
      imaging.service: console-analysis-node
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        console.network/aip-network: "true"
        app: castimaging
        imaging.service: console-analysis-node
        component: core
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorAppcastimaging | nindent 12 }}
{{- end }}
      securityContext:
        fsGroup: 10001
{{- if .Values.RestrictedSecurityMode }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      initContainers:     
{{- if .Values.RestrictedSecurityMode }}    
        - name: init-folders
          image: "{{.Values.ConsoleAnalysisNodeImage.name}}:{{.Values.ConsoleAnalysisNodeImage.tag}}"
          imagePullPolicy: "{{.Values.ConsoleAnalysisNodeImage.pullPolicy}}"
          command:
          - /bin/bash
          - -c
          - |
            rm -rf /carl-volume/*
            cp -r /home/carl/* /carl-volume/ || true
          volumeMounts:
            - name: carl-dir
              mountPath: /carl-volume
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
{{- end }}
        - name: init-folders-services-healthcheck
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
            mkdir -p {{ .Values.anadir.common }}
            mkdir -p {{ .Values.anadir.delivery }}
            mkdir -p {{ .Values.anadir.deploy }}
            mkdir -p {{ .Values.anadir.extensions }}  
{{- if .Values.EnablePostgresSSL }}
            echo "Copy postgres SSL files."
            cp /tmp/certs/* /etc/ssl/certs-postgres
            chmod 0600 /etc/ssl/certs-postgres/client-key.pem
            ls -l /etc/ssl/certs-postgres
{{- end }}    
            echo "Services healthcheck."
            until curl -s http://console-control-panel:8098/actuator/health | grep -q '"status":"UP"'; do
              echo "Waiting for console-control-panel to be healthy..."
              sleep 2
            done
            echo "console-control-panel is healthy!"
            until curl -s http://console-authentication-service:8092/actuator/health | grep -q '"status":"UP"'; do
              echo "Waiting for console-authentication-service to be healthy..."
              sleep 2
            done            
            echo "console-authentication-service is healthy!"
            echo "Done."
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.anadir.castdirmount }}
              name: castdir
            - mountPath: {{ .Values.anadir.datadirmount }}
              name: shared-datadir
{{- if .Values.EnablePostgresSSL }}
            - name: ssl-certs
              mountPath: /tmp/certs
              readOnly: true
            - name: postgres-ssl-files
              mountPath: /etc/ssl/certs-postgres
{{- end }}
        - name: postgres-upgrade
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: postgres-db-password  
            - name: OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: operator-db-password
          command:
          - /bin/sh
          - -c
          - |
            # Define connection variables
{{- if .Values.CustomPostgres.enable }}
            PG_HOST="{{ .Values.CustomPostgres.host }}"
            PG_PORT="{{ .Values.CustomPostgres.port }}"
{{- else }}
            PG_HOST="console-postgres"
            PG_PORT="2285"
{{- end }}
            echo "Running postgres upgrade..."
            PGPASSWORD="$OPERATOR_PASSWORD"
            psql -h "$PG_HOST" -p "$PG_PORT" -U operator -d postgres -f /home/imaging/sql/analysisnode-upgrade-script.sql
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
          volumeMounts:
            - name: analysisnode-upgrade-script
              mountPath: /home/imaging/sql/analysisnode-upgrade-script.sql
              subPath: analysisnode-upgrade-script.sql       
      containers:
        - env:
            - name: TMPDIR
              value: /tmp
            - name: CONTROL_PANEL_HOSTNAME
              value: console-control-panel
            - name: PORT_CONTROL_PANEL
              value: "8098"
            - name: CORE_FOLDER
              value: {{ .Values.anadir.castdirmount }}
            - name: CONSOLE_REGISTRY_URL
              value: http://console-control-panel:8098
            - name: HOST_AUTH_SERVICE
              value: console-authentication-service
            - name: PORT_AUTH_SERVICE
              value: "8092"
{{- if .Values.EnablePostgresSSL }}
            - name: CASTCONNECTIONEXTRAPARAMETERS
              value: /etc/ssl/certs-postgres/sslconfig.ini
{{- end }}
          image: "{{ .Values.ConsoleAnalysisNodeImage.name }}:{{ .Values.ConsoleAnalysisNodeImage.tag}}"
          imagePullPolicy: "{{ .Values.ConsoleAnalysisNodeImage.pullPolicy }}"
          name: console-analysis-node
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          ports:
            - containerPort: 8089
              protocol: TCP
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.AnalysisNodeResources | nindent 12 }}
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: carl-dir
              mountPath: /home/carl
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
{{- end }}
            - mountPath: {{ .Values.anadir.castdirmount }}
              name: castdir
            - mountPath: {{ .Values.anadir.datadirmount }}
              name: shared-datadir
            - name: dshm
              mountPath: /dev/shm
{{- if .Values.EnablePostgresSSL }}
            - name: postgres-ssl-files
              mountPath: /etc/ssl/certs-postgres
              readOnly: true
{{- end }}
      restartPolicy: Always 
{{- if .Values.UseImagePullSecrets }}      
      imagePullSecrets:
        - name: imagepull-sec 
{{- end }}         
      volumes:
{{- if .Values.RestrictedSecurityMode }}
        - name: carl-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
{{- end }}
        - name: shared-datadir
          persistentVolumeClaim:
            claimName: pvc-shared-datadir
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.AnalysisNode_shmsize }}
        - name: analysisnode-upgrade-script
          configMap:
            name: analysisnode-upgrade-script
{{- if .Values.EnablePostgresSSL }}
        - name: ssl-certs
          secret:
            secretName: ssl-certs
            defaultMode: 0644
        - name: postgres-ssl-files
          emptyDir: {}
{{- end }}
  volumeClaimTemplates:
    - metadata:
        name: castdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.size_castdir }}"
        storageClassName: "{{ .Values.DiskClassName }}"