apiVersion: v1
kind: Service
metadata:
  labels:
    app: castimaging
    imaging.group: console
    imaging.service: console-service
  name: console-service
  namespace: {{ .Release.Namespace }}  
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8091
  selector:
    imaging.service: console-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: castimaging
    imaging.group: console
    imaging.service: console-service
    version: {{ .Values.ConsoleServiceImage.tag| default .Values.version }}
  name: console-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ConsoleServiceReplicaCount }}
  selector:
    matchLabels:
      imaging.service: console-service
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        console.network/aip-network: "true"
        app: castimaging
        imaging.group: console
        imaging.service: console-service
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServiceSso | nindent 12 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupConsole | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorGroupViewer | nindent 12 }}
{{- end }}
{{- if .Values.RestrictedSecurityMode }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      initContainers:
      - name: console-control-panel-healthcheck
        image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
        imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
        command:
        - /bin/sh
        - -c
        - |
          until curl -s http://console-control-panel:8098/actuator/health | grep -q '"status":"UP"'; do
            echo "Waiting for console-control-panel to be healthy..."
            sleep 2
          done
          echo "console-control-panel is healthy!"
{{- if .Values.RestrictedSecurityMode }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
{{- end }}
        resources:
          {{- toYaml .Values.InitContainerResources | nindent 12 }}
      containers:
        - env:
            - name: HOST_CONSOLE
              value: console-service
            - name: PORT_CONSOLE
              value: "8091"
            - name: HOST_CONTROL_PANEL
              value: console-control-panel
            - name: PORT_CONTROL_PANEL
              value: "8098"
          image: "{{ .Values.ConsoleServiceImage.name }}:{{ .Values.ConsoleServiceImage.tag}}"
          imagePullPolicy: "{{ .Values.ConsoleServiceImage.pullPolicy }}"
          name: console-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          ports:
            - containerPort: 8091
              protocol: TCP
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 100
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.ConsoleServiceResources | nindent 12 }} 
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
{{- end }}
      volumes:
{{- if .Values.RestrictedSecurityMode }}
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
{{- end }}
      restartPolicy: Always
{{- if .Values.UseImagePullSecrets }}       
      imagePullSecrets:
        - name: imagepull-sec  
{{- end }}