apiVersion: v1
kind: Service
metadata:
  labels:
    app: castimaging
    imaging.group: console
    imaging.service: console-sso-service
  name: console-sso-service
  namespace: {{ .Release.Namespace }}  
spec:
  ports:
    - name: "8096"
      port: 8096
      targetPort: 8080
  selector:
    imaging.service: console-sso-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: castimaging
    imaging.group: console
    imaging.service: console-sso-service
    version: {{ .Values.ConsoleSSOServiceImage.tag | default .Values.version }}
  name: console-sso-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.SSOServiceReplicaCount }}
  selector:
    matchLabels:
      imaging.service: console-sso-service
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        console.network/aip-network: "true"
        app: castimaging
        imaging.group: console
        imaging.service: console-sso-service
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupConsole | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServicePostgresAnalysisNode | nindent 12 }}
            {{- toYaml .Values.labelSelectorGroupViewer | nindent 12 }}
{{- end }}
{{- if .Values.RestrictedSecurityMode }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      initContainers:
{{- if .Values.RestrictedSecurityMode }}
        - name: init-folders
          image: "{{.Values.ConsoleSSOServiceImage.name}}:{{.Values.ConsoleSSOServiceImage.tag}}"
          imagePullPolicy: "{{.Values.ConsoleSSOServiceImage.pullPolicy}}"
          command:
          - /bin/sh
          - -c
          - |
            rm -rf /keycloak-volume/*
            cp -r /opt/keycloak/* /keycloak-volume/ || true
          volumeMounts:    
            - name: keycloak-dir
              mountPath: /keycloak-volume 
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
{{- end }}
        - name: wait-for-postgres
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
{{- if .Values.CustomPostgres.enable }}
            until pg_isready -h {{ .Values.CustomPostgres.host }} -p {{ .Values.CustomPostgres.port }}; do echo waiting for postgres...; sleep 2; done; echo postgres is ready!
{{- else }}
            until pg_isready -h console-postgres -p 2285; do echo waiting for postgres...; sleep 2; done; echo postgres is ready!
{{- end }}
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
      containers:
        - env:       
{{- if .Values.CustomPostgres.enable }}
            - name: KC_DB_URL
              value: jdbc:postgresql://{{ .Values.CustomPostgres.host }}:{{ .Values.CustomPostgres.port }}/keycloak
{{- else }}
            - name: KC_DB_URL
              value: jdbc:postgresql://console-postgres:2285/keycloak
{{- end }} 
            - name: KC_DB_USERNAME
              value: operator
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: operator-db-password
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: keycloak-admin-password
            - name: KC_PROXY 
              value: "edge"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"             
{{- if .Values.ContextUrl.enable }}
            - name: KC_HOSTNAME_ADMIN_URL
              value: {{ .Values.FrontEndHost }}{{ .Values.ContextUrl.appcontext }}/auth
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HOSTNAME_URL
              value: {{ .Values.FrontEndHost }}{{ .Values.ContextUrl.appcontext }}/auth
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: PUBLIC_URL
              value: {{ .Values.FrontEndHost }}{{ .Values.ContextUrl.appcontext }}
{{- else }}
            - name: KC_PROXY_HEADERS
              value: "forwarded"
            - name: KC_HOSTNAME
              value: {{ .Values.FrontEndHost }}/auth
            - name: KC_HOSTNAME_ADMIN
              value: {{ .Values.FrontEndHost }}/auth
            - name: KEYCLOAK_FRONTEND_URL
              value: {{ .Values.FrontEndHost }}/auth
{{- end }}
          image: "{{ .Values.ConsoleSSOServiceImage.name }}:{{ .Values.ConsoleSSOServiceImage.tag}}"
          imagePullPolicy: "{{ .Values.ConsoleSSOServiceImage.pullPolicy }}"
          name: console-sso-service
          ports:
            - containerPort: 8080
              protocol: TCP
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.SSOServiceResources | nindent 12 }}
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: keycloak-dir
              mountPath: /opt/keycloak
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
{{- end }}
      restartPolicy: Always
{{- if .Values.UseImagePullSecrets }}       
      imagePullSecrets:
        - name: imagepull-sec  
{{- end }}
      volumes:
{{- if .Values.RestrictedSecurityMode }}
        - name: keycloak-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
{{- end }}      