{{- if .Values.UseCookieAdapter }}
# The cookie-adapter is only needed when SAML authentication is enabled in combination with UseIstioGateway or CreateIngress
apiVersion: v1
kind: ConfigMap
metadata:
  name: cookie-adapter-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;

        location = /healthz {
            access_log off;
            return 200 'OK';
        }
    {{- if .Values.ContextUrl.enable }}
        # Match /mycontext/auth and everything under it
        location {{ .Values.ContextUrl.appcontext }}/auth {
            # Rewrite to remove the context path before proxying
            rewrite ^{{ .Values.ContextUrl.appcontext }}(/auth/.*)$ $1 break;
            proxy_pass http://console-gateway-service:8090;
    {{- else }}
        location /auth {
            proxy_pass http://console-gateway-service:8090;
    {{- end }}
            # This targets ALL cookies (*) and sets the flags.
            proxy_cookie_flags ~ SameSite=None Secure;

            # Ensure the path remains correct
            proxy_cookie_path / /;

            # Standard proxy headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            
            proxy_buffering off;
            proxy_redirect off;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookie-adapter-nginx
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cookie-adapter
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: cookie-adapter
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServiceSso | nindent 12 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupConsole | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorGroupViewer | nindent 12 }}
{{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nginx
        image: "{{ .Values.CookieAdapterImage.name }}:{{ .Values.CookieAdapterImage.tag}}"
        imagePullPolicy: "{{ .Values.CookieAdapterImage.pullPolicy }}"
        ports:
        - containerPort: 8080
        securityContext:
  {{- if .Values.RestrictedSecurityMode }}
          readOnlyRootFilesystem: true
  {{- end }}
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
  {{- if .Values.RestrictedSecurityMode }}
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /var/cache
  {{- end }}
      volumes:
      - name: config
        configMap:
          name: cookie-adapter-config
  {{- if .Values.RestrictedSecurityMode }}
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: cookie-adapter-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: cookie-adapter
{{- end }}