{{- if .Values.ExtendProxy.enable }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- if .Values.CreateLoadBalancer }}
    helm.sh/resource-policy: keep
  {{- end }}
  {{- if and .Values.CreateLoadBalancer .Values.UseInternalLoadBalancer }}
    {{- if eq .Values.K8SProvider "AKS" }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- else if eq .Values.K8SProvider "EKS" }}
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    {{- else if eq .Values.K8SProvider "GKE" }}
    networking.gke.io/load-balancer-type: "Internal"
    {{- end }}
  {{- end }}
  labels:
    app: castimaging
    imaging.group: console
    imaging.service: extendproxy
  name: extendproxy
  namespace: {{ .Release.Namespace }}  
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    console.service: extendproxy
  {{- if .Values.CreateLoadBalancer }}
  type: LoadBalancer
  {{- end }}
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: castimaging
    imaging.group: console
    imaging.service: extendproxy
    version: {{ .Values.ExtendProxyImage.tag| default .Values.version }}
  name: extendproxy
  namespace: {{ .Release.Namespace }}   
spec:
  replicas: {{ .Values.ExtendProxyReplicaCount }}
  selector:
    matchLabels:
      imaging.service: extendproxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        console.network/aip-network: "true"
        app: castimaging
        imaging.group: console
        imaging.service: extendproxy
        console.service: extendproxy
    spec:
  {{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServiceSso | nindent 12 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupConsole | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorGroupViewer | nindent 12 }}
  {{- end }}
      securityContext:
        fsGroup: 1001
  {{- if .Values.RestrictedSecurityMode }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  {{- end }}
      initContainers:
  {{- if .Values.RestrictedSecurityMode }}
        - name: init-folders
          image: "{{.Values.ExtendProxyImage.name}}:{{.Values.ExtendProxyImage.tag}}"
          imagePullPolicy: "{{.Values.ExtendProxyImage.pullPolicy}}"
          command:
          - /bin/bash
          - -c
          - |
            rm -rf /opt-volume/*
            cp -r /opt/* /opt-volume/ 
          volumeMounts:    
            - name: opt-dir
              mountPath: /opt-volume 
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
  {{- end }}
      containers:
        - env:
            - name: host_port
              value: "8085"
            - name: host_name
              value: "{{ .Values.ExtendProxy.exthostname }}"
            - name: ext_public_url
              value: "https://extend.castsoftware.com"
            - name: public_url
  {{- if or (.Values.CreateIngress) (.Values.UseIstioGateway) }}
    {{- if (ne .Values.ExtendProxy.exthostname (urlParse .Values.FrontEndHost).hostname) }}
              value: "https://{{ .Values.ExtendProxy.exthostname }}"
    {{- else }}
              value: "https://{{ .Values.ExtendProxy.exthostname }}/extendproxy"
    {{- end }}  
  {{- else }}
              value: "http://{{ regexReplaceAll ":[0-9]+$" (.Values.ExtendProxy.exthostname) "" }}:8085"
  {{- end }}
            - name: platform
              value: "linux_x64"
          image: "{{ .Values.ExtendProxyImage.name }}:{{ .Values.ExtendProxyImage.tag}}"
          imagePullPolicy: "{{ .Values.ExtendProxyImage.pullPolicy }}"
          name: extendproxy
          ports:
            - containerPort: 8085
              protocol: TCP 
  {{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
  {{- end }}
          resources:
            {{- toYaml .Values.ExtendProxyResources | nindent 12 }}
          volumeMounts:
  {{- if .Values.RestrictedSecurityMode }}
            - name: opt-dir
              mountPath: /opt
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
  {{- end }} 
            - mountPath: /opt/cast_extend_proxy/data
              name: extendproxy
      restartPolicy: Always
  {{- if .Values.UseImagePullSecrets }}       
      imagePullSecrets:
        - name: imagepull-sec   
  {{- end }}
      volumes:
  {{- if .Values.RestrictedSecurityMode }}
        - name: opt-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}  
  {{- end }}
        - name: extendproxy
          persistentVolumeClaim:
            claimName: pvc-extendproxy-data
{{- end }}