kind: Service
apiVersion: v1
metadata:
  name: viewer-server
  labels:
    app: viewer-server
spec:
  ports:
    - name: http
      port: 8083
      targetPort: 8080
    - name: login
      port: 9000
      targetPort: 9000
  selector:
    app: viewer-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: viewer-server
    version: {{.Values.ViewerServiceImage.tag| default .Values.version}}
  name: viewer-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ViewerServerReplicaCount }}
  selector:
    matchLabels:
      app: viewer-server
  template:
    metadata:
      labels:
        app: viewer-server
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:      
        - name: neo4j-and-control-panel-healthcheck
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
            until curl -s http://console-control-panel:8098/actuator/health | grep -q '"status":"UP"'; do
              echo "Waiting for console-control-panel to be healthy..."
              sleep 2
            done
            echo "console-control-panel is healthy!"  
            until wget --no-verbose --spider http://viewer-neo4j:7474; do 
              echo "Waiting for neo4j..."
              sleep 2
            done
            echo "viewer-neo4j is up!"         
      containers:
        - image: "{{ .Values.ViewerServiceImage.name }}:{{ .Values.ViewerServiceImage.tag}}"
          imagePullPolicy: "{{ .Values.ViewerServiceImage.pullPolicy }}"
          command: ['sh', '-c', "/opt/imaging/config/init.sh"]
          name: viewer-server
          env:
            - name: TZ
              value: "UTC"
            - name: EUREKA_HOST
              value: "console-control-panel"
            - name: EUREKA_PORT
              value: "8098"
            - name: SERVICE_HOST
              value: "viewer-server"
            - name: SERVER_PORT
              value: "9000"
            - name: NEO4J_BOLT_ENDPOINT
              value: "viewer-neo4j:7687"
            - name: LOG_LEVEL
              value: "debug"
            - name: FE_PORT
              value: "8083"
            - name: QUERY_TIMEOUT
              value: "60"
            - name: NEO4J_PASSWORD
              value: "imaging"
{{- if .Values.ContextUrl.enable }}
            - name: APP_CONTEXT
              value: {{ .Values.ContextUrl.appcontext }}
{{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          resources:
            {{- toYaml .Values.ViewerServerServiceResources | nindent 12 }}
          volumeMounts:
            - name: log
              mountPath: /opt/imaging/imaging-service/logs
            - name: servernginxconf
              mountPath: /opt/imaging/config/nginx/conf/nginx.conf
              subPath: nginx.conf
{{- if .Values.UseImagePullSecrets }}               
      imagePullSecrets:
        - name: imagepull-sec
{{- end }}        
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: pvc-imagingviewer-v3-server-log
        - name: servernginxconf
          configMap:
            name: servernginxconf