apiVersion: v1
kind: Service
metadata:
  name: viewer-neo4j
  labels:
    app: viewer-neo4j
    component: core
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: browser
    - port: 7687
      targetPort: 7687
      name: bolt
    - port: 7473
      targetPort: 7473
      name: https
  selector:
    app: viewer-neo4j
    component: core
---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: viewer-neo4j-core
  namespace: {{.Release.Namespace}}
spec:
  serviceName: viewer-neo4j
  replicas: {{.Values.ViewerNeo4jReplicaCount}}
  selector:
    matchLabels:
      app: viewer-neo4j
  template:
    metadata:
      labels:
        app: viewer-neo4j
        component: core
    spec:
      securityContext:
        fsGroup: 7474
      containers:
        - name: viewer-neo4j
          image: "{{.Values.ViewerNeo4jImage.name}}:{{.Values.ViewerNeo4jImage.tag}}"
          imagePullPolicy: "{{.Values.ViewerNeo4jImage.pullPolicy}}"
          command: ['sh', '-c', "/var/lib/neo4j/config/init.sh"]
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_HEAP_SIZE
              value: "{{ .Values.NEO4J_HEAP_SIZE | default "12G" }}"
            - name: NEO4J_TRANSACTION_MEMORY
              value: "{{ .Values.NEO4J_TRANSACTION_MEMORY | default "10G" }}"
            - name: TZ
              value: "UTC"
            - name: NEO4J_USERNAME
              value: "neo4j"
            - name: NEO4J_PASSWORD
              value: "imaging"
            - name: LOG_LEVEL
              value: "debug"
            - name: PODMAN_ENV
              value: "false"
{{- if .Values.ContextUrl.enable }}
            - name: APP_CONTEXT
              value: {{ .Values.ContextUrl.appcontext }}
{{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 7474
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 7474
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          ports:
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
          resources:
            {{- toYaml .Values.ViewerNeo4jResources | nindent 12 }}
          volumeMounts:
            - name: neo4jdata
              mountPath: /logs
              subPathExpr: logs
            - name: neo4jdata
              mountPath: /var/lib/neo4j/config/neo4j5_data
              subPathExpr: neo4jdata
            - name: neo4jdata
              mountPath: /var/lib/neo4j/config/csv/archive
              subPathExpr: csvarchive                    
{{- if .Values.UseImagePullSecrets }}              
      imagePullSecrets:
        - name: imagepull-sec
{{- end }}        
  volumeClaimTemplates:
    - metadata:
        name: neo4jdata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ .Values.DiskClassName }}"
        resources:
          requests:
            storage: "{{ .Values.size_neo4jdata }}"
