apiVersion: v1
kind: Service
metadata:
  labels:
    app: castimaging
    imaging.group: console
    imaging.service: console-authentication-service
  name: console-authentication-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "8092"
      port: 8092
      targetPort: 8092
  selector:
    imaging.service: console-authentication-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: castimaging
    imaging.group: console
    imaging.service: console-authentication-service
    version: {{ .Values.ConsoleAuthenticationServiceImage.tag| default .Values.version }}
  namespace: {{ .Release.Namespace }}
  name: console-authentication-service
spec:
  replicas: {{ .Values.AuthenticationServiceReplicaCount }}
  selector:
    matchLabels:
      imaging.service: console-authentication-service
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        console.network/aip-network: "true"
        app: castimaging
        imaging.group: console
        imaging.service: console-authentication-service
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServiceSso | nindent 12 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupConsole | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorGroupViewer | nindent 12 }}
{{- end }}
{{- if .Values.RestrictedSecurityMode }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      initContainers:
{{- if .Values.RestrictedSecurityMode }}
        - name: init-folders
          image: "{{.Values.ConsoleAuthenticationServiceImage.name}}:{{.Values.ConsoleAuthenticationServiceImage.tag}}"
          imagePullPolicy: "{{.Values.ConsoleAuthenticationServiceImage.pullPolicy}}"
          command:
          - /bin/sh
          - -c
          - |
            rm -rf /cast-volume/*
            cp -r /cast/* /cast-volume/ || true
          volumeMounts:    
            - name: cast-dir
              mountPath: /cast-volume 
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 100
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
{{- end }}
        - name: wait-for-postgres
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
{{- if .Values.CustomPostgres.enable }}
            until pg_isready -h {{ .Values.CustomPostgres.host }} -p {{ .Values.CustomPostgres.port }}; do echo waiting for postgres...; sleep 2; done; echo postgres is ready!
{{- else }}
            until pg_isready -h console-postgres -p 2285; do echo waiting for postgres...; sleep 2; done; echo postgres is ready!
{{- end }}
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
        - name: console-control-panel-healthcheck
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
            until curl -s http://console-control-panel:8098/actuator/health | grep -q '"status":"UP"'; do
              echo "Waiting for console-control-panel to be healthy..."
              sleep 10
            done
            echo "console-control-panel is healthy!"       
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
      containers:
        - env:
{{- if .Values.UseCustomTrustStore }}
            - name: USE_CUSTOM_TRUSTSTORE
              value: "true"
            - name: TRUSTSTORE_PATH
              value: /cast/truststore.jks
            - name: TRUSTSTORE_PASSWORD
              value: castapi
{{- end }}                      
            - name: HOST_AUTH_SERVICE
              value: console-authentication-service
            - name: PORT_AUTH_SERVICE
              value: "8092"
            - name: HOST_CONTROL_PANEL
              value: console-control-panel
            - name: PORT_CONTROL_PANEL
              value: "8098"
            - name: HOST_KEYCLOAK
              value: console-sso-service
            - name: PORT_KEYCLOAK
              value: "8096"
{{- if .Values.CustomPostgres.enable }}
            - name: DB_HOST
              value: {{ .Values.CustomPostgres.host }}
            - name: DB_PORT
              value: "{{ .Values.CustomPostgres.port }}"               
{{- else }}
            - name: DB_HOST
              value: console-postgres
            - name: DB_PORT
              value: "2285"
{{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: operator-db-password
            - name: KC_USER
              value: "admin"
            - name: KC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: keycloak-admin-password
            - name: HOST_GATEWAY
              value: console-gateway-service
            - name: PORT_GATEWAY
              value: "8090"
            - name: MULTI_TENANCY_ENABLED
              value: "{{ .Values.MultiTenancyEnabled }}"
{{- if .Values.ContextUrl.enable }}
            - name: NGINX_HOST
              value: {{ .Values.FrontEndHost }}{{ .Values.ContextUrl.appcontext }}
            - name: APP_CONTEXT
              value: {{ .Values.ContextUrl.appcontext }}
{{- else }}
            - name: NGINX_HOST
              value: {{ .Values.FrontEndHost }}
{{- end }}
          image: "{{ .Values.ConsoleAuthenticationServiceImage.name }}:{{ .Values.ConsoleAuthenticationServiceImage.tag }}"
          imagePullPolicy: "{{ .Values.ConsoleAuthenticationServiceImage.pullPolicy }}"
          name: console-authentication-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          ports:
            - containerPort: 8092
              protocol: TCP
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 100
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.AuthenticationServiceResources | nindent 12 }}
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: cast-dir
              mountPath: /cast
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
{{- end }}
{{- if .Values.UseCustomTrustStore }}
            - name: authcacrt
              mountPath: /cast/certs/ca.crt
              subPath: ca.crt
{{- end }}
      volumes:
{{- if .Values.RestrictedSecurityMode }}
        - name: cast-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
{{- end }}
{{- if .Values.UseCustomTrustStore }}
        - name: authcacrt
          configMap:
            name: authcacrt           
{{- end }}
      restartPolicy: Always
{{- if .Values.UseImagePullSecrets }}      
      imagePullSecrets:
        - name: imagepull-sec
{{- end }}        