{{- if .Values.UseImagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.Base64EncodedDockerconfigjson }}
kind: Secret
metadata:
  name: imagepull-sec
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: imaging-pwd-sec
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
# Encoding command (Linux): echo -n "mypassword" | base64
  postgres-db-password: {{ .Values.PostgresDbPassword | default "cG9zdGdyZXM=" }}
  operator-db-password: {{ .Values.OperatorDbPassword | default "Q2FzdEFJUA==" }}
  guest-db-password: {{ .Values.GuestDbPassword | default "V2VsY29tZVRvQUlQ" }}
  keycloak-db-password: {{ .Values.KeycloakDbPassword | default "a2V5Y2xvYWs=" }}
  keycloak-admin-password: {{ .Values.KeycloakAdminPassword | default "YWRtaW4=" }}
  neo4j-password: {{ .Values.Neo4jPassword | default "aW1hZ2luZw==" }}