apiVersion: v1
kind: Service
metadata:
  name: viewer-neo4j
  labels:
    app: castimaging
    imaging.group: viewer
    imaging.service: viewer-neo4j
    component: core
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: browser
    - port: 7687
      targetPort: 7687
      name: bolt
    - port: 7473
      targetPort: 7473
      name: https
  selector:
    imaging.service: viewer-neo4j
    component: core
---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  labels:
    app: castimaging
    imaging.group: viewer
    imaging.service: viewer-neo4j  
  name: viewer-neo4j-core
  namespace: {{.Release.Namespace}}
spec:
  serviceName: viewer-neo4j
  replicas: {{.Values.ViewerNeo4jReplicaCount}}
  selector:
    matchLabels:
      imaging.service: viewer-neo4j
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: castimaging
        imaging.group: viewer
        imaging.service: viewer-neo4j
        component: core
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupViewer | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServicePostgresAnalysisNode | nindent 12 }}
            {{- toYaml .Values.labelSelectorGroupConsole | nindent 12 }}
{{- end }}
      securityContext:
        fsGroup: 7474
{{- if .Values.RestrictedSecurityMode }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
{{- if .Values.RestrictedSecurityMode }}
      initContainers:      
        - name: init-folders
          image: "{{.Values.ViewerNeo4jImage.name}}:{{.Values.ViewerNeo4jImage.tag}}"
          imagePullPolicy: "{{.Values.ViewerNeo4jImage.pullPolicy}}"
          command:
          - /bin/bash
          - -c
          - |
            rm -rf /neo4j-var-volume/*
            cp -r /var/* /neo4j-var-volume/ || true
          volumeMounts:
            - name: neo4j-var-dir
              mountPath: /neo4j-var-volume
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 7474
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
{{- end }}
      containers:
        - name: viewer-neo4j
          image: "{{.Values.ViewerNeo4jImage.name}}:{{.Values.ViewerNeo4jImage.tag}}"
          imagePullPolicy: "{{.Values.ViewerNeo4jImage.pullPolicy}}"
          command: ['sh', '-c', "/var/lib/neo4j/config/init.sh"]
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_server_memory_heap_initial__size
              value: "{{ .Values.NEO4J_server_memory_heap_initial__size }}"
            - name: NEO4J_server_memory_heap_max__size
              value: "{{ .Values.NEO4J_server_memory_heap_max__size }}"
            - name: NEO4J_dbms_memory_transaction_total_max
              value: "{{ .Values.NEO4J_dbms_memory_transaction_total_max }}"
            - name: TZ
              value: "UTC"
            - name: NEO4J_USERNAME
              value: "neo4j"
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: neo4j-password
            - name: LOG_LEVEL
              value: "debug"
            - name: PODMAN_ENV
              value: "false"
            - name: NEO4J_BOLT_ENDPOINT
              value: "bolt://viewer-neo4j:7687"
{{- if .Values.ContextUrl.enable }}
            - name: APP_CONTEXT
              value: {{ .Values.ContextUrl.appcontext }}
{{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 7474
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 7474
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          ports:
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 7474
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.ViewerNeo4jResources | nindent 12 }}
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: neo4j-var-dir
              mountPath: /var
            - name: tmp
              mountPath: /tmp
{{- end }}
            - name: neo4jdata
              mountPath: /logs
              subPathExpr: logs
            - name: neo4jdata
              mountPath: /var/lib/neo4j/config/neo4j5_data
              subPathExpr: neo4jdata
            - name: neo4jdata
              mountPath: /var/lib/neo4j/config/csv/archive
              subPathExpr: csvarchive                    
{{- if .Values.UseImagePullSecrets }}              
      imagePullSecrets:
        - name: imagepull-sec
{{- end }}        
      volumes:
{{- if .Values.RestrictedSecurityMode }}
        - name: neo4j-var-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
{{- end }}
  volumeClaimTemplates:
    - metadata:
        name: neo4jdata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ .Values.DiskClassName }}"
        resources:
          requests:
            storage: "{{ .Values.size_neo4jdata }}"
