kind: Service
apiVersion: v1
metadata:
  name: viewer-aimanager
  labels:
    app: castimaging
    imaging.group: viewer
    imaging.service: viewer-aimanager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    imaging.service: viewer-aimanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: castimaging
    imaging.group: viewer
    imaging.service: viewer-aimanager
    version: {{.Values.ViewerAiManagerImage.tag| default .Values.version}}
  name: viewer-aimanager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ViewerAiManagerReplicaCount }}
  selector:
    matchLabels:
      imaging.service: viewer-aimanager
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: castimaging
        imaging.group: viewer
        imaging.service: viewer-aimanager
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServiceNeo4j | nindent 12 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupViewer | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorGroupConsole | nindent 12 }}
{{- end }}
      securityContext:
        fsGroup: 1000
{{- if .Values.RestrictedSecurityMode }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      initContainers:
{{- if .Values.RestrictedSecurityMode }}
        - name: init-folders
          image: "{{.Values.ViewerAiManagerImage.name}}:{{.Values.ViewerAiManagerImage.tag}}"
          imagePullPolicy: "{{.Values.ViewerAiManagerImage.pullPolicy}}"
          command:
          - /bin/sh
          - -c
          - |
            rm -rf /open-ai-volume/*
            cp -r /opt/imaging/open_ai-manager/* /open-ai-volume/ || true
          volumeMounts:    
            - name: open-ai-dir
              mountPath: /open-ai-volume 
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
{{- end }}
        - name: neo4j-and-control-panel-healthcheck
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
            until curl -s http://console-control-panel:8098/actuator/health | grep -q '"status":"UP"'; do
              echo "Waiting for console-control-panel to be healthy..."
              sleep 2
            done
            echo "console-control-panel is healthy!"  
            until wget --no-verbose --spider http://viewer-neo4j:7474; do 
              echo "Waiting for neo4j..."
              sleep 2
            done
            echo "viewer-neo4j is up!"                           
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: open-ai-dir
              mountPath: /opt/imaging/open_ai-manager
{{- end }}
      containers:
        - env:
            - name: TZ
              value: "UTC"
            - name: NEO4J_BOLT_ENDPOINT
              value: "bolt://viewer-neo4j:7687"
            - name: LOG_LEVEL
              value: "debug"
            - name: EUREKA_HOST
              value: "console-control-panel"
            - name: EUREKA_PORT
              value: "8098"
            - name: SERVICE_HOST
              value: "viewer-aimanager"
            - name: AIMANAGER_PORT
              value: "8082"
            - name: ETL_PORT
              value: "9001"
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: neo4j-password
{{- if .Values.ContextUrl.enable }}
            - name: APP_CONTEXT
              value: {{ .Values.ContextUrl.appcontext }}
{{- end }}
          image: "{{ .Values.ViewerAiManagerImage.name }}:{{ .Values.ViewerAiManagerImage.tag}}"
          imagePullPolicy: "{{ .Values.ViewerAiManagerImage.pullPolicy }}"
          command: ['sh', '-c', "/opt/imaging/open_ai-manager/config/init.sh"]
          name: viewer-aimanager
          ports:
            - containerPort: 8082
              protocol: TCP
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.ViewerAiManagerResources | nindent 12 }}
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: open-ai-dir
              mountPath: /opt/imaging/open_ai-manager
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
{{- end }}  
            - name: logdir
              mountPath: /opt/imaging/open_ai-manager/logs
              readOnly: false         
{{- if .Values.UseImagePullSecrets }}               
      imagePullSecrets:
        - name: imagepull-sec
{{- end }}        
      volumes:
        - name: logdir
          persistentVolumeClaim:
            claimName: pvc-imagingviewer-v3-aimanager-logs
{{- if .Values.RestrictedSecurityMode }}
        - name: open-ai-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
{{- end }}
        - name: updated-config-volume
          emptyDir: {}            
        - name: db-creds
          secret:
            secretName: imaging-pwd-sec            