kind: Service
apiVersion: v1
metadata:
  name: viewer-etl
  labels:
    app: castimaging
    imaging.group: viewer
    imaging.service: viewer-etl
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 9001
    targetPort: 9001
  selector:
    imaging.service: viewer-etl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: castimaging
    imaging.group: viewer
    imaging.service: viewer-etl
    version: {{.Values.ViewerEtlImage.tag| default .Values.version}}
  name: viewer-etl
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ViewerEtlReplicaCount }}
  selector:
    matchLabels:
      imaging.service: viewer-etl
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: castimaging
        imaging.group: viewer
        imaging.service: viewer-etl
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServiceNeo4j | nindent 12 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupViewer | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorGroupConsole | nindent 12 }}
{{- end }}
      securityContext:
        fsGroup: 1000
{{- if .Values.RestrictedSecurityMode }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      initContainers:
{{- if .Values.RestrictedSecurityMode }}
        - name: init-folders
          image: "{{ .Values.ViewerEtlImage.name }}:{{ .Values.ViewerEtlImage.tag }}"
          imagePullPolicy: "{{ .Values.ViewerEtlImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
            rm -rf /etl-volume/*
            cp -r /opt/imaging/imaging-etl/* /etl-volume/ || true
          volumeMounts:    
            - name: etl-dir
              mountPath: /etl-volume 
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
{{- end }}
        - name: neo4j-and-control-panel-healthcheck
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
{{- if .Values.EnablePostgresSSL }}
            echo "Copy postgres SSL files."
            cp /tmp/certs/* /etc/ssl/certs-postgres
            ls -l /etc/ssl/certs-postgres
{{- end }}
            until curl -s http://console-control-panel:8098/actuator/health | grep -q '"status":"UP"'; do
              echo "Waiting for console-control-panel to be healthy..."
              sleep 2
            done
            echo "console-control-panel is healthy!"  
            until wget --no-verbose --spider http://viewer-neo4j:7474; do 
              echo "Waiting for neo4j..."
              sleep 2
            done
            echo "viewer-neo4j is up!"
            until curl -s http://viewer-server:9000/healthcheck | grep -q "I am alive"; do
              echo "Waiting for viewer-server..."
              sleep 2
            done
            echo "viewer-server is up!"
            echo "Done."
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
          volumeMounts:
{{- if .Values.EnablePostgresSSL }}
            - name: ssl-certs
              mountPath: /tmp/certs
              readOnly: true
            - name: postgres-ssl-files
              mountPath: /etc/ssl/certs-postgres
{{- end }}
      containers:
        - env:
            - name: TZ
              value: "UTC"
            - name: EUREKA_HOST
              value: "console-control-panel"
            - name: EUREKA_PORT
              value: "8098"
            - name: SERVICE_HOST
              value: "viewer-etl"
            - name: ETL_PORT
              value: "9001"
            - name: NEO4J_BOLT_ENDPOINT
              value: "bolt://viewer-neo4j:7687"
            - name: LOG_LEVEL
              value: "debug"
            - name: WORKER_POOL_SIZE
              value: "4"
            - name: NEO4J_IMPORT_BATCH_SIZE
              value: "1000"
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: neo4j-password
{{- if .Values.EnablePostgresSSL }}
            - name: CASTCONNECTIONEXTRAPARAMETERS
              value: /etc/ssl/certs-postgres/sslconfig.ini
{{- end }}
{{- if .Values.ContextUrl.enable }}
            - name: APP_CONTEXT
              value: {{ .Values.ContextUrl.appcontext }}
{{- end }}
          image: "{{ .Values.ViewerEtlImage.name }}:{{ .Values.ViewerEtlImage.tag}}"
          imagePullPolicy: "{{ .Values.ViewerEtlImage.pullPolicy }}"
          command: ['sh', '-c', '/opt/imaging/imaging-etl/config/init.sh']
          name: viewer-etl
          ports:
            - containerPort: 9001
              protocol: TCP
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.ViewerEtlResources | nindent 12 }}
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: etl-dir
              mountPath: /opt/imaging/imaging-etl
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
{{- end }}
            - name: logdir
              mountPath: /opt/imaging/imaging-etl/logs
              readOnly: false
            - name: csvarchive
              mountPath: /opt/imaging/imaging-etl/upload/archive
{{- if .Values.EnablePostgresSSL }}
            - name: postgres-ssl-files
              mountPath: /etc/ssl/certs-postgres
              readOnly: true
{{- end }}
{{- if .Values.UseImagePullSecrets }}              
      imagePullSecrets:
        - name: imagepull-sec
{{- end }}        
      volumes:
{{- if .Values.RestrictedSecurityMode }}
        - name: etl-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}  
{{- end }}
        - name: logdir
          persistentVolumeClaim:
            claimName: pvc-imagingviewer-v3-etl-logs
        - name: csvarchive
          persistentVolumeClaim:
            claimName: pvc-imagingviewer-v3-etl-csvarchive
{{- if .Values.EnablePostgresSSL }}
        - name: ssl-certs
          secret:
            secretName: ssl-certs
            defaultMode: 0644
        - name: postgres-ssl-files
          emptyDir: {}
{{- end }}