kind: Service
apiVersion: v1
metadata:
  name: viewer-api
  labels:
    app: castimaging
    imaging.group: viewer
    imaging.service: viewer-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8070
    targetPort: 8070
  selector:
    imaging.service: viewer-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: castimaging
    imaging.group: viewer
    imaging.service: viewer-api
    version: {{.Values.ViewerApiImage.tag| default .Values.version}}
  name: viewer-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ViewerApiReplicaCount }}
  selector:
    matchLabels:
      imaging.service: viewer-api
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: castimaging
        imaging.group: viewer
        imaging.service: viewer-api
    spec:
{{- if .Values.EnforceNodeAffinity }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.nodeSelectorAppcastimaging | nindent 12 }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorServiceNeo4j | nindent 12 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.podAffinityGroupViewer | nindent 12 }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- toYaml .Values.labelSelectorGroupConsole | nindent 12 }}
{{- end }}
      securityContext:
        fsGroup: 1000
{{- if .Values.RestrictedSecurityMode }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      initContainers:
{{- if .Values.RestrictedSecurityMode }}
        - name: init-folders
          image: "{{.Values.ViewerApiImage.name}}:{{.Values.ViewerApiImage.tag}}"
          imagePullPolicy: "{{.Values.ViewerApiImage.pullPolicy}}"
          command:
          - /bin/sh
          - -c
          - |
            rm -rf /config-volume/*
            cp -r /opt/imaging/imaging-api/config/* /config-volume/ || true
          volumeMounts:    
            - name: config-dir
              mountPath: /config-volume 
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
{{- end }} 
        - name: neo4j-and-control-panel-healthcheck
          image: {{ .Values.InitUtilImage.name }}:{{ .Values.InitUtilImage.tag }}
          imagePullPolicy: "{{ .Values.InitUtilImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - |
            until curl -s http://console-control-panel:8098/actuator/health | grep -q '"status":"UP"'; do
              echo "Waiting for console-control-panel to be healthy..."
              sleep 2
            done
            echo "console-control-panel is healthy!"  
            until wget --no-verbose --spider http://viewer-neo4j:7474; do 
              echo "Waiting for neo4j..."
              sleep 2
            done
            echo "viewer-neo4j is up!"
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.InitContainerResources | nindent 12 }}
      containers:
        - env:
            - name: TZ
              value: "UTC"
            - name: LOG_LEVEL
              value: "debug"
            - name: EUREKA_HOST
              value: "console-control-panel"
            - name: EUREKA_PORT
              value: "8098"
            - name: SERVICE_HOST
              value: "viewer-api"
            - name: IMAGING_APIS_PORT
              value: "8070"
            - name: NEO4J_BOLT_ENDPOINT
              value: "bolt://viewer-neo4j:7687"
            - name: API_KEY
              value: 
            - name: SOURCE_CODE_SERVICE_TOKEN
              value: 
            - name: SOURCE_CODE_SERVICE_ENDPOINT
              value: 
            - name: TRUSTED_PROXIES
              value: 
            - name: ACCESS_CONTROL_ALLOW_ORIGIN
              value: 
            - name: ACCESS_CONTROL_ALLOW_METHODS
              value: 
            - name: ACCESS_CONTROL_ALLOW_HEADERS
              value: 
            - name: QUERY_TIMEOUT
              value: "60"
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imaging-pwd-sec
                  key: neo4j-password
{{- if .Values.ContextUrl.enable }}
            - name: APP_CONTEXT
              value: {{ .Values.ContextUrl.appcontext }}
{{- end }}
          image: "{{ .Values.ViewerApiImage.name }}:{{ .Values.ViewerApiImage.tag }}"
          imagePullPolicy: "{{ .Values.ViewerApiImage.pullPolicy }}"
          command: ['sh', '-c', "/opt/imaging/imaging-api/config/init.sh"]
          name: viewer-api
          ports:
            - containerPort: 8070
              protocol: TCP
{{- if .Values.RestrictedSecurityMode }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
{{- end }}
          resources:
            {{- toYaml .Values.ViewerApiResources | nindent 12 }}
          volumeMounts:
{{- if .Values.RestrictedSecurityMode }}
            - name: config-dir
              mountPath: /opt/imaging/imaging-api/config
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
{{- end }}
            - name: logdir
              mountPath: /opt/imaging/imaging-api/logs
              readOnly: false          
      volumes:
{{- if .Values.RestrictedSecurityMode }}
        - name: config-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
{{- end }}
        - name: logdir
          persistentVolumeClaim:
            claimName: pvc-imagingviewer-v3-api-logs
{{- if .Values.UseImagePullSecrets }}              
      imagePullSecrets:
        - name: imagepull-sec
{{- end }}  